
const STORAGE_KEY="followUpAppLocalLeadsV2";
const state={leads:[],currentView:"todayView",selectedLeadId:null};
const $=id=>document.getElementById(id);
function todayISO(){return new Date().toISOString().slice(0,10)}
function formatDate(d){if(!d)return"";const [y,m,day]=d.split("-");return `${m}/${day}/${y}`}
function isDue(lead){return lead.followUpDate<=todayISO()&&lead.status!=="Closed"&&lead.status!=="Dead"}
function isOverdue(lead){return lead.followUpDate<todayISO()&&lead.status!=="Closed"&&lead.status!=="Dead"}
function generateId(){return crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random().toString(16).slice(2)}
function saveLeads(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.leads))}
function normalizeLead(lead){return{id:lead.id||generateId(),name:lead.name||"",phone:lead.phone||"",email:lead.email||"",propertyAddress:lead.propertyAddress||lead.address||"",status:lead.status||"New",followUpDate:lead.followUpDate||todayISO(),notes:lead.notes||"",lastCompletedFollowUp:lead.lastCompletedFollowUp||"",createdAt:lead.createdAt||todayISO(),updatedAt:lead.updatedAt||todayISO()}}
function loadLeads(){const raw=localStorage.getItem(STORAGE_KEY)||localStorage.getItem("followUpAppLocalLeadsV1");if(!raw){state.leads=[normalizeLead({name:"Sample Seller",phone:"5551234567",email:"seller@example.com",propertyAddress:"123 Main St, Atlanta, GA",status:"Follow-Up Needed",followUpDate:todayISO(),notes:"This is a sample lead. Delete it after testing."})];saveLeads();return}try{state.leads=JSON.parse(raw).map(normalizeLead);saveLeads()}catch{state.leads=[]}}
function showView(viewId){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$(viewId).classList.add("active");state.currentView=viewId;$("todayTab").classList.toggle("active",viewId==="todayView");$("leadsTab").classList.toggle("active",viewId==="leadsView");$("toolsTab").classList.toggle("active",viewId==="toolsView");render()}
function render(){$("todayText").textContent=new Date().toLocaleDateString(undefined,{weekday:"long",month:"short",day:"numeric"});renderToday();renderLeadList();if(state.selectedLeadId)renderDetail(state.selectedLeadId)}
function escapeHTML(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function leadCardHTML(lead){const dueClass=isOverdue(lead)?"overdue":isDue(lead)?"due-today":"";const dueLabel=isOverdue(lead)?"Overdue":isDue(lead)?"Due Today":formatDate(lead.followUpDate);return `<div class="card lead-card" data-id="${lead.id}"><div class="lead-title-row"><div class="lead-name">${escapeHTML(lead.name||"Unnamed Lead")}</div><span class="${dueClass}">${dueLabel}</span></div><div class="lead-address">${escapeHTML(lead.propertyAddress||"No address entered")}</div><div class="meta-row"><span class="status-pill">${escapeHTML(lead.status)}</span><span>${formatDate(lead.followUpDate)}</span></div></div>`}
function attachLeadCardClicks(containerId){document.querySelectorAll(`#${containerId} .lead-card`).forEach(card=>card.addEventListener("click",()=>openDetail(card.dataset.id)))}
function renderToday(){const due=state.leads.filter(isDue).sort((a,b)=>a.followUpDate.localeCompare(b.followUpDate));$("dueCount").textContent=due.length;$("todayList").innerHTML=due.length?due.map(leadCardHTML).join(""):`<div class="card empty">No follow-ups due. Add a lead or use Test Follow-Up Now.</div>`;attachLeadCardClicks("todayList")}
function renderLeadList(){const search=$("searchInput").value.trim().toLowerCase();const filter=$("statusFilter").value;const filtered=state.leads.filter(l=>{const hay=[l.name,l.phone,l.email,l.propertyAddress,l.status,l.notes].join(" ").toLowerCase();return(!search||hay.includes(search))&&(!filter||l.status===filter)}).sort((a,b)=>a.followUpDate.localeCompare(b.followUpDate));$("leadList").innerHTML=filtered.length?filtered.map(leadCardHTML).join(""):`<div class="card empty">No leads found.</div>`;attachLeadCardClicks("leadList")}
function openDetail(id){state.selectedLeadId=id;renderDetail(id);showView("detailView")}
function renderDetail(id){const lead=state.leads.find(x=>x.id===id);if(!lead)return;$("detailName").textContent=lead.name||"Lead Detail";const clean=(lead.phone||"").replace(/\D/g,"");$("detailCard").innerHTML=`<div class="detail-field"><div class="detail-label">Address</div><div class="detail-value">${escapeHTML(lead.propertyAddress||"Not entered")}</div></div><div class="detail-field"><div class="detail-label">Phone</div><div class="detail-value">${escapeHTML(lead.phone||"Not entered")}</div></div><div class="detail-field"><div class="detail-label">Email</div><div class="detail-value">${escapeHTML(lead.email||"Not entered")}</div></div><div class="action-grid"><a href="${clean?`tel:${clean}`:"#"}">Call</a><a href="${clean?`sms:${clean}`:"#"}">Text</a><a href="${lead.email?`mailto:${lead.email}`:"#"}">Email</a></div><div class="detail-field"><div class="detail-label">Status</div><div class="detail-value">${escapeHTML(lead.status)}</div></div><div class="detail-field"><div class="detail-label">Follow-Up Date</div><div class="detail-value">${formatDate(lead.followUpDate)}</div></div><div class="detail-field"><div class="detail-label">Last Completed</div><div class="detail-value">${lead.lastCompletedFollowUp?formatDate(lead.lastCompletedFollowUp):"No completed follow-up yet"}</div></div><div class="detail-field"><div class="detail-label">Notes</div><div class="detail-value">${escapeHTML(lead.notes||"No notes yet")}</div></div><div class="detail-actions"><button class="complete-btn" onclick="markComplete('${lead.id}')">Mark Complete + Tomorrow</button><button class="warning-btn" onclick="testFollowUpNow('${lead.id}')">Test Follow-Up Now</button><button class="edit-btn" onclick="editLead('${lead.id}')">Edit Lead</button><button class="delete-btn" onclick="deleteLead('${lead.id}')">Delete Lead</button></div>`}
function openAddForm(){$("formTitle").textContent="Add Lead";$("leadForm").reset();$("leadId").value="";$("followUpDate").value=todayISO();$("status").value="New";showView("formView")}
function editLead(id){const l=state.leads.find(x=>x.id===id);if(!l)return;$("formTitle").textContent="Edit Lead";$("leadId").value=l.id;$("name").value=l.name;$("phone").value=l.phone;$("email").value=l.email;$("propertyAddress").value=l.propertyAddress;$("status").value=l.status;$("followUpDate").value=l.followUpDate;$("notes").value=l.notes;showView("formView")}
function saveForm(e){e.preventDefault();const id=$("leadId").value||generateId();const idx=state.leads.findIndex(x=>x.id===id);const old=idx>=0?state.leads[idx]:null;const lead=normalizeLead({id,name:$("name").value.trim(),phone:$("phone").value.trim(),email:$("email").value.trim(),propertyAddress:$("propertyAddress").value.trim(),status:$("status").value,followUpDate:$("followUpDate").value||todayISO(),notes:$("notes").value.trim(),lastCompletedFollowUp:old?.lastCompletedFollowUp||"",createdAt:old?.createdAt||todayISO(),updatedAt:todayISO()});if(idx>=0)state.leads[idx]=lead;else state.leads.push(lead);saveLeads();state.selectedLeadId=id;showView("detailView")}
function markComplete(id){const l=state.leads.find(x=>x.id===id);if(!l)return;const t=new Date();t.setDate(t.getDate()+1);l.lastCompletedFollowUp=todayISO();l.followUpDate=t.toISOString().slice(0,10);l.status="Contacted";l.updatedAt=todayISO();saveLeads();renderDetail(id);render()}
function testFollowUpNow(id){const l=state.leads.find(x=>x.id===id);if(!l)return;l.followUpDate=todayISO();l.status="Follow-Up Needed";l.updatedAt=todayISO();saveLeads();renderDetail(id);render();alert("Test follow-up triggered. This lead is now due today.")}
function deleteLead(id){if(!confirm("Delete this lead?"))return;state.leads=state.leads.filter(x=>x.id!==id);saveLeads();state.selectedLeadId=null;showView("leadsView")}
function clearAllLeads(){if(!confirm("This deletes every lead stored on this device. Export a backup first. Continue?"))return;state.leads=[];saveLeads();state.selectedLeadId=null;render();showView("todayView")}
function csvEscape(v){const s=String(v??"");return/[",\n\r]/.test(s)?`"${s.replaceAll('"','""')}"`:s}
function downloadText(content,filename,type){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
function exportCSV(){const h=["id","name","phone","email","propertyAddress","status","followUpDate","lastCompletedFollowUp","createdAt","updatedAt","notes"];const rows=state.leads.map(l=>h.map(k=>csvEscape(l[k])).join(","));downloadText([h.join(","),...rows].join("\n"),`follow-up-leads-${todayISO()}.csv`,"text/csv")}
function exportJSON(){downloadText(JSON.stringify({app:"Follow Up App",version:2,exportedAt:new Date().toISOString(),leads:state.leads},null,2),`follow-up-backup-${todayISO()}.json`,"application/json")}
function parseCSV(text){const rows=[];let cur=[],field="",q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&q&&n==='"'){field+='"';i++}else if(c==='"'){q=!q}else if(c===","&&!q){cur.push(field);field=""}else if((c==="\n"||c==="\r")&&!q){if(c==="\r"&&n==="\n")i++;cur.push(field);rows.push(cur);cur=[];field=""}else field+=c}cur.push(field);rows.push(cur);return rows.filter(r=>r.some(c=>c.trim()!==""))}
function importFile(){const file=$("importFileInput").files[0];if(!file){alert("Choose a CSV or JSON backup first.");return}const reader=new FileReader();reader.onload=()=>{try{let imported=[];if(file.name.toLowerCase().endsWith(".json")){const parsed=JSON.parse(reader.result);imported=Array.isArray(parsed)?parsed:parsed.leads||[]}else{const rows=parseCSV(reader.result);const headers=rows.shift().map(h=>h.trim());imported=rows.map(row=>{const item={};headers.forEach((h,i)=>item[h]=row[i]||"");return item})}let added=0,updated=0;imported.map(normalizeLead).forEach(n=>{const i=state.leads.findIndex(e=>e.id===n.id);if(i>=0){state.leads[i]=n;updated++}else{state.leads.push(n);added++}});saveLeads();render();alert(`Import complete. Added ${added}. Updated ${updated}.`);showView("leadsView")}catch(e){alert("Import failed. Make sure the file is a valid backup CSV or JSON.")}};reader.readAsText(file)}
function wireEvents(){$("todayTab").addEventListener("click",()=>showView("todayView"));$("leadsTab").addEventListener("click",()=>showView("leadsView"));$("toolsTab").addEventListener("click",()=>showView("toolsView"));$("addLeadBottomBtn").addEventListener("click",openAddForm);$("addLeadTopBtn").addEventListener("click",openAddForm);$("cancelFormBtn").addEventListener("click",()=>showView("leadsView"));$("backToLeadsBtn").addEventListener("click",()=>showView("leadsView"));$("leadForm").addEventListener("submit",saveForm);$("searchInput").addEventListener("input",renderLeadList);$("statusFilter").addEventListener("change",renderLeadList);$("exportCsvBtn").addEventListener("click",exportCSV);$("exportJsonBtn").addEventListener("click",exportJSON);$("importBtn").addEventListener("click",importFile);$("clearAllBtn").addEventListener("click",clearAllLeads)}
loadLeads();wireEvents();$("followUpDate").value=todayISO();render();
if("serviceWorker"in navigator){navigator.serviceWorker.register("service-worker.js").catch(()=>{})}
